### ISSUE TITLE
Failes to request headers from wordpress.org

### ISSUE THREAD

**Issue by Songtronix** [http-rs/surf#151]
```Rust
[2020-03-20T12:06:44Z INFO  scrape_headers] Visit Headers from 'https://wordpress.org'
[2020-03-20T12:06:44Z DEBUG isahc::agent] agent waker listening on 127.0.0.1:55110
[2020-03-20T12:06:44Z DEBUG isahc::agent] agent took 1.103154ms to start up
[2020-03-20T12:06:44Z INFO  surf::middleware::logger::native] sending request
[2020-03-20T12:06:44Z DEBUG isahc::agent] agent ready
[2020-03-20T12:06:44Z DEBUG isahc::handler] initializing handler for request [id=0]
[2020-03-20T12:06:44Z DEBUG isahc::handler]   Trying 198.143.164.252:443...
[2020-03-20T12:06:44Z DEBUG isahc::handler] Connected to wordpress.org (198.143.164.252) port 443 (#0)
[2020-03-20T12:06:44Z DEBUG isahc::handler] ALPN, offering h2
[2020-03-20T12:06:44Z DEBUG isahc::handler] ALPN, offering http/1.1
[2020-03-20T12:06:44Z DEBUG isahc::handler] successfully set certificate verify locations:
[2020-03-20T12:06:44Z DEBUG isahc::handler]   CAfile: /etc/ssl/certs/ca-certificates.crt
      CApath: none
[2020-03-20T12:06:44Z DEBUG isahc::handler] TLSv1.3 (OUT), TLS handshake, Client hello (1):
[2020-03-20T12:06:44Z DEBUG isahc::handler] TLSv1.3 (IN), TLS handshake, Server hello (2):
[2020-03-20T12:06:44Z DEBUG isahc::handler] TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
[2020-03-20T12:06:44Z DEBUG isahc::handler] TLSv1.3 (IN), TLS handshake, Certificate (11):
[2020-03-20T12:06:44Z DEBUG isahc::handler] TLSv1.3 (IN), TLS handshake, CERT verify (15):
[2020-03-20T12:06:44Z DEBUG isahc::handler] TLSv1.3 (IN), TLS handshake, Finished (20):
[2020-03-20T12:06:44Z DEBUG isahc::handler] TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
[2020-03-20T12:06:44Z DEBUG isahc::handler] TLSv1.3 (OUT), TLS handshake, Finished (20):
[2020-03-20T12:06:44Z DEBUG isahc::handler] SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
[2020-03-20T12:06:44Z DEBUG isahc::handler] ALPN, server accepted to use h2
[2020-03-20T12:06:44Z DEBUG isahc::handler] Server certificate:
[2020-03-20T12:06:44Z DEBUG isahc::handler]  subject: OU=Domain Control Validated; CN=*.wordpress.org
[2020-03-20T12:06:44Z DEBUG isahc::handler]  start date: Nov  6 17:42:01 2017 GMT
[2020-03-20T12:06:44Z DEBUG isahc::handler]  expire date: Dec 15 20:11:21 2020 GMT
[2020-03-20T12:06:44Z DEBUG isahc::handler]  subjectAltName: host "wordpress.org" matched cert's "wordpress.org"
[2020-03-20T12:06:44Z DEBUG isahc::handler]  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
[2020-03-20T12:06:44Z DEBUG isahc::handler]  SSL certificate verify ok.
[2020-03-20T12:06:44Z DEBUG isahc::handler] Using HTTP2, server supports multi-use
[2020-03-20T12:06:44Z DEBUG isahc::handler] Connection state changed (HTTP/2 confirmed)
[2020-03-20T12:06:44Z DEBUG isahc::handler] Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
[2020-03-20T12:06:44Z DEBUG isahc::handler] Using Stream ID: 1 (easy handle 0x55c592198cb0)
[2020-03-20T12:06:44Z DEBUG isahc::handler] TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
[2020-03-20T12:06:44Z DEBUG isahc::handler] TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
[2020-03-20T12:06:44Z DEBUG isahc::handler] old SSL session ID is stale, removing
[2020-03-20T12:06:44Z DEBUG isahc::handler] Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
[2020-03-20T12:06:44Z DEBUG isahc::handler] Connection #0 to host wordpress.org left intact
[2020-03-20T12:06:44Z INFO  surf::middleware::logger::native] request completed
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ToStrError { _priv: () }', /home/songtronix/.cargo/registry/src/github.com-1ecc6299db9ec823/surf-2.0.0-alpha.0/src/headers.rs:60:48
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  14: <surf::headers::Iter as core::iter::traits::iterator::Iterator>::next
  15: <std::future::GenFuture<T> as core::future::future::Future>::poll
  16: std::thread::local::LocalKey<T>::with
  17: std::thread::local::LocalKey<T>::with
  18: async_std::task::block_on::block_on
  19: scrape_headers::main
  20: std::rt::lang_start::{{closure}}
  21: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  22: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  23: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  24: std::panicking::try
             at src/libstd/panicking.rs:281
  25: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  26: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  27: main
  28: __libc_start_main
  29: _start
```

Headers returned by https://wordpress.org : 
```HTTP
Server: nginx
Date: Fri, 20 Mar 2020 12:05:47 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Vary: Accept-Encoding
Strict-Transport-Security: max-age=360
X-Olaf: â
X-Frame-Options: SAMEORIGIN
X-nc: HIT ord 1
Content-Encoding: gzip
```

Probably X-Olaf causes issues and to be honest wordpress is the only site which uses it (https://webtechsurvey.com/response-headers/x-olaf/).

Version used: *2.0.0-alpha.0*

**Comment by goto-bus-stop** [comment]
thanks for the report! it does look rare but it's probably not great to crash on non-utf8 headers anyways.
