### ISSUE TITLE
thread 'main' panicked at 'Could not convert into a valid `StatusCode`: Invalid status code', /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/http-types-2.12.0/src/response.rs:63:14

### ISSUE THREAD

**Issue by bbigras** [http-rs/surf#350]
I think the service is returning a bad error code (520).

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::expect
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1035:23
   4: http_types::response::Response::new
             at /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/http-types-2.12.0/src/response.rs:61:22
   5: <http_client::isahc::IsahcClient as http_client::HttpClient>::send::{{closure}}
             at /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/http-client-6.5.3/src/isahc.rs:63:28
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
   8: surf::client::Client::send::{{closure}}::{{closure}}::{{closure}}
             at /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/surf-2.3.2/src/client.rs:211:45
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  11: <surf::middleware::logger::native::Logger as surf::middleware::Middleware>::handle::{{closure}}
             at /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/surf-2.3.2/src/middleware/logger/native.rs:46:40
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  13: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  14: surf::client::Client::send::{{closure}}
             at /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/surf-2.3.2/src/client.rs:223:40
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  16: <surf::request_builder::RequestBuilder as core::future::future::Future>::poll::{{closure}}
             at /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/surf-2.3.2/src/request_builder.rs:421:67
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  18: <surf::request_builder::RequestBuilder as core::future::future::Future>::poll
             at /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/surf-2.3.2/src/request_builder.rs:425:9
```

**Comment by jbr** [comment]
This the same as #348
